language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  
# command to install dependencies
install: pip install -r dev-requirements.txt

# command to run tests
script: python -m unittest discover aws_requests_auth
